# Generated by Django 5.1 on 2024-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('height', models.FloatField()),
                ('point_id', models.IntegerField(unique=True)),
                ('characteristics', models.JSONField(default=list)),
            ],
        ),
    ]
