# Generated by Django 5.1 on 2024-09-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('height', models.FloatField()),
                ('point_id', models.IntegerField(unique=True)),
                ('characteristics', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('characteristics', models.JSONField(default=list)),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='myapp.point')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='myapp.point')),
            ],
            options={
                'unique_together': {('point1', 'point2')},
            },
        ),
    ]
