sentiment_lexicon_es = {
    "bueno": 1.5,
    "excelente": 2.0,
    "fantástico": 2.0,
    "genial": 1.8,
    "maravilloso": 2.0,
    "increíble": 2.0,
    "feliz": 1.8,
    "satisfecho": 1.5,
    "hermoso": 2.0,
    "cómodo": 1.5,
    "relajante": 1.7,
    "pacífico": 1.7,
    "espectacular": 2.0,
    "emocionante": 1.8,
    "divertido": 1.5,
    "bonito": 1.5,
    "agradable": 1.5,
    "seguro": 1.5,
    "tranquilo": 1.7,
    
    "malo": -1.5,
    "terrible": -2.0,
    "horrible": -2.0,
    "pésimo": -2.0,
    "desagradable": -1.8,
    "decepcionante": -1.8,
    "inseguro": -1.5,
    "incómodo": -1.5,
    "difícil": -1.2,
    "estresante": -1.7,
    "molesto": -1.5,
    "feo": -1.5,
    "ruidoso": -1.5,
    "sucio": -1.8,
    "caro": -1.5,
    "aburrido": -1.5,
    "peligroso": -2.0,
    
    "no": -0.5,  # Inversor de sentimiento básico
    "nunca": -0.5,
    "jamás": -0.5,
    "menos": -0.5,
    "ni": -0.5,
    "tampoco": -0.5,
    
    # # Palabras neutrales comunes
    # "acampada": 0.0,
    # "montaña": 0.0,
    # "tienda": 0.0,
    # "noche": 0.0,
    # "día": 0.0,
    # "grupo": 0.0,
    # "lugar": 0.0,
    # "camino": 0.0,
    # "comida": 0.0,
    # "agua": 0.0,
    # "aire": 0.0,
    # "fuego": 0.0,
    # "amigos": 0.0,
}
